### ISSUE TITLE
Assembly deep references

### ISSUE THREAD

**Issue by TyrelBaux** [jduv/AppDomainToolkit#11]
Hi im new using this toolkit, 

If i call LoadAssemblyWithReferences and my dll have references in the references this dont load it then i change the method to 

```javascript
public IList<Assembly> LoadAssemblyWithReferences(LoadMethod loadMethod, string assemblyPath)
{
    var assembly = this.LoadAssembly(loadMethod, assemblyPath);

    Dictionary<string, AssemblyName> listFound = new Dictionary<string, AssemblyName>();
    List<Assembly> results = new List<Assembly>();
    Stack stack = new Stack();

    results.Add(assembly);

    AssemblyName[] an = assembly.GetReferencedAssemblies();

    for (int i = an.Length - 1; i >= 0; --i)
    {
        listFound.Add(an[i].Name, an[i]);
        stack.Push(an[i]);
    }

    while (stack.Count > 0)
    {
        var info = (AssemblyName)stack.Pop();

        Assembly child = Assembly.Load(info.Name);
        results.Add(child);

        AssemblyName[] subchild = child.GetReferencedAssemblies();
        for (int i = subchild.Length - 1; i >= 0; --i)
        {
            if (!listFound.ContainsKey(subchild[i].Name))
            {
                listFound.Add(subchild[i].Name, subchild[i]);
                stack.Push(subchild[i]);
            }
        }
    }

    return results;
}
```
And this load all the references tree...
Sorry i dont know how to make a "pull request" and i dont know if this go help..

**Comment by jduv** [comment]
This is a pretty specialized situation. I expect extending the assembly loader is probably your best bet here. I don't think I want to go down the rabbit hole of supporting dependency graphs--as some interesting problems would need to be solved there (i.e. how far down the rabbit hole does one go?). So, keep rolling with what you have, but I don't think I'll be integrating this into the toolkit unless there's more demand.
