### ISSUE TITLE
IDisposable usage is not intuitive

### ISSUE THREAD

**Issue by fnajera-rac-de** [jduv/AppDomainToolkit#18]
Hi,

First of all, thanks for the library!
While I was implementing my code with this library, I ran into an interesting issue with a piece of code that, at first glance, seems fairly normal:

```C#
using (var context = AppDomainContext.Create())
{
    using (var proxy = Remote<MyType>.CreateProxy(context.Domain))
    {

    }
}
```

By the dispose of the inner block, **both** the proxy and the wrapped AppDomain are disposed (and therefore the AppDomain is unloaded), and by the dispose of the outer block, there is an exception because it tries to re-unload the wrapped appdomain (the appdomain wrapper object for the context is different than the appdomain wrapper for the proxy, and it is still not marked as disposed, so it thinks the appdomain is still up and running).

I've seen the code and the readme file, and I think that the idea is, if you use Remote.CreateProxy, then you shouldn't dispose the context by hand. However, this is counterintuitive in two fronts:

1. it seems odd to have a IDisposable object (context) that you must NOT dispose, and more importantly,
2. what if you create more than one proxy via Remote.CreateProxy? You then must dispose just one of them, and not the others or the context.

Anyway, it's not a bug per-se, but I thought it was worth mentioning.

Thanks,

Fernando Nájera

**Comment by kellyelton** [comment]
Yeah I agree with you, proxy shouldn't dispose the context, should be the other way around though.

**Comment by jduv** [comment]
Some excellent observations. Let me take a look and re-discover exactly what I was thinking :).

**Comment by jduv** [comment]
I agree with this. The proxy should not dispose the context. However, as the domain we cannot keep track of remotes that utilize us without a registration mechanism of some kind--so I think we should probably not support that.

**Comment by kellyelton** [comment]
If we're talking intuitive, I think it'd be a bit more intuitive for only have to dispose the context when you're done with it. However I can see why you wouldn't want to do that.
