### ISSUE TITLE
Unable to see how this can work when the assemblies being loaded are not known to the host at compile time

### ISSUE THREAD

**Issue by rdavi10471a2** [jduv/AppDomainToolkit#19]
Please advise if this scenerio is possible.
Attempting to use this library to support plugins. where the plugins implement a simiple interface with a Run() method (that will display its own form etc)
From the examples provided I don't see a way to crea ta proxy on the host side of things that can interact with the assembly loaded in the app domain.  I know I must be missing something...  I dont want the host to have to have the dlls being loaded and executed in its reference list.
please advise

**Comment by rdavi10471a2** [comment]
Here is an example of what I am trying to do.
The DLL including  TestFrm.DSFRM definition must be included in the project for this to work...
This DLL is a plugin and I don't want it loaded in the host unless inside the app domain. I attempted to use an interface implemented by DSFRM but that would not compile either

            using (var context = AppDomainContext.Create())
            {
                context.LoadAssembly(LoadMethod.LoadFrom, @"C:\Users\rdavi_000\Documents\visual studio 2013\Projects\DealershipSeerWindows\TestFrm\bin\Debug\TestFRM.DLL");

                var result = RemoteFunc.Invoke(
                    context.Domain,
                    "Run",
                    (phrase) =>
                    {
                        return new TestFrm.DSFRM("blah");
                    });

                // Executes in the remote domain.
                result.Run();
            }

**Comment by rdavi10471a2** [comment]
Here is the Form class defined in the plugin DLL
public partial class DSFRM : Form , DealershipSeerInterfaces.DSMDIForm
    {
        public Form FormInstance { get { return this; } }
        
       
        

        public DSFRM(object o)
        {
            InitializeComponent();
            this.FormClosing+=DSFRM_FormClosing;
        }

        void DSFRM_FormClosing(object sender, EventArgs e)
        {

            MessageBox.Show("Child form closed in child  "+AppDomain.CurrentDomain.FriendlyName);
            
    
        }
        private void DSFRM_Load(object sender, EventArgs e)
        {
            
           
        }

        private void button1_Click(object sender, EventArgs e)
        {
            this.Close();
           // Application.Exit();
        }

        public void Run()
        {

            this.ShowDialog();
        }
       

    }

and the interface definition that is in a shared DLL
public interface DSMDIForm
    {

      // Form  FormInstance {get;}
       void Run();
       
   //    event EventHandler FormClosingEvent;

       
    }

**Comment by rdavi10471a2** [comment]
This works.. but is not what i want b/c there is no way to not have DSFRM defined in the parent domain
   

using (var context = AppDomainContext.Create())
            {
                context.LoadAssembly(LoadMethod.LoadFrom, @"C:\Users\rdavi_000\Documents\visual studio 2013\Projects\DealershipSeerWindows\TestFrm\bin\Debug\TestFRM.DLL");

                //how to do this without having  a refernce to DSFRM in the main project
                var RemoteForm = Remote<DSFRM>.CreateProxy(context.Domain);
                RemoteForm.RemoteObject.ShowDialog();

               
            }

**Comment by jduv** [comment]
So I'm fairly certain that's not possible without using dynamics. The remote has to know what kind of proxy it's creating methinks. Give it a try by passing Dynamic into the Remote.CreateProxy call and let me know if that doesn't work.

Sorry, day jobs are hard ;).
