### ISSUE TITLE
Examples of hot swapping assemblies

### ISSUE THREAD

**Issue by pvanroos** [jduv/AppDomainToolkit#22]
@jduv 

Great library.  Do you have any examples of hot swapping assemblies and calling methods on those classes using reflection?  My use case requires loading a "plugin", calling a method on that plugin, unloading that plugin and then replacing with a new version, and then calling a method on that newly loaded plugin.

Is that possible with this library?

**Comment by jduv** [comment]
Hi @pvanroos, thanks man. I wish I had kept it a little more maintained ;). 

It's possible through remote functions. When you dispose the app domain context, the library should, in theory, go out of context. If that doesn't work let me know and I'll give it a look.

**Comment by JoeBrockhaus** [comment]
This is actually something I implemented a couple of years ago but never got back to updating this library with those changes. I'll try to find time this week to dig thay up and work it in.

**Comment by pvanroos** [comment]
I eventually came up with a solution.  It's not ideal but I think it will work for now.  I have a single 5-node ServiceFabric cluster running on Azure.  I have 4 services I distribute across the cluster.  One service processes the job queue (service bus) and another service processes the actual job type that was added to the queue.  The job processing service, at startup, loads plugins from a blob storage account--by streaming in the DLL byte arrays and loads them directly into, here's the key, the current domain (not a new separate app domain).   Once loaded, I use job configuration information to instantiate and call the types needed to execute the job using reflection.  I realize this has potential problems but when I want to make an update to any plugin, I update the DLLs in blob storage and submit a RestartReplica call to the job processing service in the cluster.  This will cause the cluster to reload the replicas and reload the plugins (assemblies).   I'm leaving out some details for simplicity sake but you get my drift.

Future iterations could use an Azure function that triggers when an update is made to a plugin in storage and notifies the job processing service to reload the updated plugin's assembly(s).    If I could make AppDomains work, I could load each plugin into a separate AppDomain and unload the AppDomain when updates are needed without a need to restart the replicas.

**Comment by jduv** [comment]
@pvanroos After reading your question a second time I believe I did exactly what you want in my masters project implementation, which is WinBert. In that project I dynamically execute a set of fuzzed randoop tests on two different instances of the code that is built by Visual Studio. Start here:

https://github.com/jduv/WinBert/blob/master/Arktos.WinBert/Testing/TestManager.cs

Follow ```executeStack``` through.
